spring:
  datasource:
    username: root
    password: abc123
    url: jdbc:mysql://192.168.62.31:3306/glm_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.62.31:8848
  application:
    name: glm-ware
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  zipkin:
    base-url: http://192.168.62.31:9411/    # zipkin 服务器的地址
    discovery-client-enabled: false # 关闭服务发现，否则 Spring Cloud 会把 zipkin 的 url 当做服务名称
    sender:
      type: web # 设置使用 http 的方式传输数据
    sleuth:
      sampler:
        probability: 1  # 设置抽样采集率为 100% ，默认为 0.1 ，即 10%

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 11000

logging:
  level:
    com.example.ware: debug
