spring:
  datasource:
    username: root
    password: abc123
    url: jdbc:mysql://192.168.62.31:3306/glm_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.62.31
    virtual-host: /
    port: 5672
    publisher-confirm-type: correlated
    publisher-returns: true
#    只要抵达队列，以异步发送优先回调return confirm
    template:
      mandatory: true
    listener:
      simple:
#        手动确认接受消息
        acknowledge-mode: manual
  application:
    name: glm-order

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 9000
